dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
    - script: mvn test -Punit-tests -Dspring.profiles.active=mysql-travis
    - script: mvn test -Pe2e-tests -Dspring.profiles.active=mysql-travis
    - script: mvn test -Pintegration-tests -Dspring.profiles.active=mysql-travis
